# Generated by Django 5.2 on 2025-05-06 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_student_enrollment_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=uuid.uuid4, help_text='Unique identifier for the student', max_length=60, unique=True),
        ),
    ]
