# Generated by Django 5.2 on 2025-05-06 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=uuid.uuid4, help_text='Unique identifier for the student', max_length=10, unique=True),
        ),
    ]
